export const GET_VIDEOS_LOADING = "GET_VIDEOS_LOADING";
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS";
export const GET_VIDEOS_FAILURE = "GET_VIDEOS_FAILURE";

export const GET_CHANNEL_LOADING = "GET_CHANNEL_LOADING";
export const GET_CHANNEL_SUCCESS = "GET_CHANNEL_SUCCESS";
export const GET_CHANNEL_FAILURE = "GET_CHANNEL_FAILURE";
